databaseChangeLog:
  - changeSet:
      id: create_schema_aetna
      author: workwithdante
      changes:
        - sql:
            dbms: postgresql
            sql: |
              CREATE SCHEMA IF NOT EXISTS aetna;
      rollback:
        - sql:
            dbms: postgresql
            sql: |
              DROP SCHEMA IF EXISTS aetna CASCADE;

  - changeSet:
      id: create_unlogged_temp_aetna
      author: workwithdante
      preConditions:
        - dbms:
            type: postgresql
      changes:
        - createTable:
            schemaName: aetna
            tableName: temp
            tableOptions: UNLOGGED
            columns:
              - column:
                  name: Member Name
                  type: text
              - column:
                  name: Relationship
                  type: text
              - column:
                  name: Plan ID
                  type: text
              - column:
                  name: Metal Tier
                  type: text
              - column:
                  name: Marketplace
                  type: text
              - column:
                  name: Subscriber Status
                  type: text
              - column:
                  name: Issuer Assigned ID
                  type: text
              - column:
                  name: Effective Date
                  type: text
              - column:
                  name: Financial Status
                  type: text
              - column:
                  name: Autopay Status
                  type: text
              - column:
                  name: Paid Through Date
                  type: text
      rollback:
        - dropTable:
            schemaName: aetna
            tableName: temp

  - changeSet:
      id: create_view_bs_aetna
      author: workwithdante
      preConditions:
        - dbms:
            type: postgresql
      changes:
        - createView:
            schemaName: aetna
            viewName: bs
            replaceIfExists: true
            selectQuery: |
              SELECT
                temp.*
              FROM aetna.temp AS temp
              WHERE temp."Relationship" = 'Self';
      rollback:
        - dropView:
            schemaName: aetna
            viewName: bs
            cascade: true
